# Site settings
title: My Github Blog
email: 
description: Records and remarks 
# baseurl: "" # the subpath of your site, e.g. /blog/
url: "zhuzelong.github.io" # the base hostname & protocol for your site
github_username:  zhuzelong

# Build settings
markdown: kramdown

# From Solar theme
permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
# ----------------